### ISSUE TITLE
GitHub organisation oauth returns 500 error if you're not a member instead of 403

### ISSUE THREAD

**Issue by manics** [jupyterhub/oauthenticator#167]
Expected behaviour: If GitHub organisation oauth is enabled and you're not a member JupyterHub should return a `403 Forbidden` status.

Observed behaviour: `500 Internal Server Error`

zero-to-jupyterhub-k8s config with https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/501:
```
hub:
  db:
    type: sqlite-memory
  image:
    name: manics/k8s-hub
    tag: pr501
  extraConfig: |
    c.JupyterHub.log_level = 'DEBUG'
    c.Spawner.debug = True

proxy:
  secretToken: "[SECRET_TOKEN]"
  service:
    type: NodePort

singleuser:
  storage:
    type: none

auth:
  type: github
  github:
    clientId: "[CLIENT_ID]"
    clientSecret: "[CLIENT_SECRET]"
    callbackUrl: "http://10.0.17.150.xip.io/hub/oauth_callback"
    org_whitelist:
    - not-a-member-org

ingress:
  enabled: true
  hosts:
  - 10.0.17.150.xip.io
```

`kubectl logs -f deploy/hub`:
```
[I 2018-02-22 11:02:12.981 JupyterHub oauth2:82] OAuth redirect: 'http://10.0.17.150.xip.io/hub/oauth_callback'
[I 2018-02-22 11:02:12.982 JupyterHub log:122] 302 GET /hub/oauth_login?next= → https://github.com/login/oauth/authorize?redirect_uri=http%3A%2F%2F10.0.17.150.xip.io%2Fhub%2Foauth_callback&client_id=[CLIENT_ID]&response_type=code&state=[STATE]%3D%3D&scope=read%3Aorg (@134.36.162.197) 1.30ms
[E 2018-02-22 11:02:14.321 JupyterHub web:1591] Uncaught exception GET /hub/oauth_callback?code=adaab6f7c8e2958ef574&state=[STATE]%3D%3D (134.36.162.197)
    HTTPServerRequest(protocol='http', host='10.0.17.150.xip.io', method='GET', uri='/hub/oauth_callback?code=adaab6f7c8e2958ef574&state=[STATE]%3D%3D', version='HTTP/1.1', remote_ip='134.36.162.197', headers={'Upgrade-Insecure-Requests': '1', 'Dnt': '1', 'Cookie': '_jsuid=2043919642; _xsrf=2|c617c272|20e16f593395ce0f101faea8944095be|1519211408; oauthenticator-state="2|1:0|10:1519297332|20:oauthenticator-state|120:ZXlKemRHRjBaVjlwWkNJNklDSmpaR0ptTXpnd01EYzVOR1EwT0RjM09XUmhNamswWm1Vek9EZzRPVGt6T0NJc0lDSnVaWGgwWDNWeWJDSTZJQ0lpZlE9PQ==|fac7a5a197c7a88c613bfb0c43e2588336fd70765d9bcf7a768c59f8a10e53a3"', 'Referer': 'http://10.0.17.150.xip.io/hub/login', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-GB,en;q=0.7,en-US;q=0.3', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0', 'X-Original-Forwarded-For': '134.36.162.197', 'X-Scheme': 'http', 'X-Original-Uri': '/hub/oauth_callback?code=adaab6f7c8e2958ef574&state=[STATE]%3D%3D', 'X-Forwarded-Proto': 'http,http', 'X-Forwarded-Port': '80,80', 'X-Forwarded-Host': '10.0.17.150.xip.io', 'X-Forwarded-For': '134.36.162.197,10.233.126.16', 'X-Real-Ip': '134.36.162.197', 'Connection': 'close', 'Host': '10.0.17.150.xip.io'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 328, in login_user
        authenticated = yield self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 227, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/github.py", line 137, in authenticate
        user_in_org = yield self._check_organization_whitelist(org, username, access_token)
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/github.py", line 171, in _check_organization_whitelist
        resp = yield http_client.fetch(req)
    tornado.httpclient.HTTPError: HTTP 404: Not Found

[D 2018-02-22 11:02:14.323 JupyterHub base:633] No template for 500
[E 2018-02-22 11:02:14.328 JupyterHub log:114] {
      "Upgrade-Insecure-Requests": "1",
      "Dnt": "1",
      "Cookie": "_jsuid=2043919642; _xsrf=2|c617c272|20e16f593395ce0f101faea8944095be|1519211408; oauthenticator-state=\"2|1:0|10:1519297332|20:oauthenticator-state|120:ZXlKemRHRjBaVjlwWkNJNklDSmpaR0ptTXpnd01EYzVOR1EwT0RjM09XUmhNamswWm1Vek9EZzRPVGt6T0NJc0lDSnVaWGgwWDNWeWJDSTZJQ0lpZlE9PQ==|fac7a5a197c7a88c613bfb0c43e2588336fd70765d9bcf7a768c59f8a10e53a3\"",
      "Referer": "http://10.0.17.150.xip.io/hub/login",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-GB,en;q=0.7,en-US;q=0.3",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:58.0) Gecko/20100101 Firefox/58.0",
      "X-Original-Forwarded-For": "134.36.162.197",
      "X-Scheme": "http",
      "X-Original-Uri": "/hub/oauth_callback?code=adaab6f7c8e2958ef574&state=[STATE]%3D%3D",
      "X-Forwarded-Proto": "http,http",
      "X-Forwarded-Port": "80,80",
      "X-Forwarded-Host": "10.0.17.150.xip.io",
      "X-Forwarded-For": "134.36.162.197,10.233.126.16",
      "X-Real-Ip": "134.36.162.197",
      "Connection": "close",
      "Host": "10.0.17.150.xip.io"
    }
[E 2018-02-22 11:02:14.328 JupyterHub log:122] 500 GET /hub/oauth_callback?code=adaab6f7c8e2958ef574&state=[STATE]%3D%3D (@134.36.162.197) 969.11ms
[D 2018-02-22 11:02:14.402 JupyterHub log:122] 304 GET /favicon.ico (@134.36.162.197) 0.56ms
```

Originally reported in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/501#issuecomment-367311371

**Comment by manics** [comment]
Sorry, this was my mistake. I tested with a non-existent github org, but this means the GitHub API call to fetch the organisation failed leading to the 500 error.
