### ISSUE TITLE
Using oauthenticator with helm

### ISSUE THREAD

**Issue by jreadey** [jupyterhub/oauthenticator#176]
I've setup a basic JupyterHub instance following the ZeroToJupyterHub guide.
Now I'd like to customize my env to support Auth0.  I added the following to my config.yaml file:

```auth:
  type: auth0
  auth0:
    clientId: <clientid>
    clientSecret: <clientsecret>
    callbackUrl:  http://myjupyterhub.myorg.org/hub/oauth_callback
```
But on running the helm upgrade I get this error in the JupyterHub node:
```$ kubectl --namespace hdflab log hub-6987bd858c-8hf9s
[E 2018-03-25 23:45:30.192 JupyterHub app:1623]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1620, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/lib/python3.6/types.py", line 204, in __next__
        return next(self.__wrapped)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1358, in initialize
        self.load_config_file(self.config_file)
      File "<decorator-gen-5>", line 2, in load_config_file
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 598, in load_config_file
        raise_config_file_errors=self.raise_config_file_errors,
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.6/dist-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/usr/local/lib/python3.6/dist-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/srv/jupyterhub_config.py", line 183, in <module>
        raise ValueError("Unhandled auth type: %r" % auth_type)
    ValueError: Unhandled auth type: 'auth0'
```
This is jupyterhub-v0.6.  Is oauthenticator not included with this release?

TIA!

**Comment by minrk** [comment]
oauthenticator is included, but I think auth0 hasn't been set up in the jupyterhub helm chart. Can you add an issue [over there](https://github.com/jupyterhub/zero-to-jupyterhub-k8s) for auth0 support?

**Comment by philvarner** [comment]
Issue filed https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1435

This issue should likely be closed.

**Comment by minrk** [comment]
thanks @philvarner!
