### ISSUE TITLE
GenericOAuthenticator fails after successfully getting a token

### ISSUE THREAD

**Issue by rizwansaeed** [jupyterhub/oauthenticator#184]
I'm trying to set up a hub using zero-to-jupyterhub-k8s with minikube and using Okta as an auth provider. I successfully manage to get a token from Okta but when I come back to my hub I get a 500: Internal Server Error. Looking in the logs I see the following:

```
[E 2018-04-24 17:14:22.670 JupyterHub web:1591] Uncaught exception GET /hub/oauth_callback?code=66q4WVNOIyxWEYHVLvTN&amp;state=eyJzdGF0ZV9pZCI6ICI2NzUwNzZjZmU5MTQ0OTBkOTI3NjFkYTA1OWEzZTFhNSIsICJuZXh0X3VybCI6ICIifQ%3D%3D (172.17.0.1)
    HTTPServerRequest(protocol='http', host='fbn-jph:31212', method='GET', uri='/hub/oauth_callback?code=66q4WVNOIyxWEYHVLvTN&amp;state=eyJzdGF0ZV9pZCI6ICI2NzUwNzZjZmU5MTQ0OTBkOTI3NjFkYTA1OWEzZTFhNSIsICJuZXh0X3VybCI6ICIifQ%3D%3D', version='HTTP/1.1', remote_ip='172.17.0.1', headers={'Accept-Language': 'en-gb', 'Accept-Encoding': 'gzip, deflate', 'Referer': 'http://fbn-jph:31212/hub/login', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Cookie': 'oauthenticator-state="2|1:0|10:1524590061|20:oauthenticator-state|120:ZXlKemRHRjBaVjlwWkNJNklDSTJOelV3TnpaalptVTVNVFEwT1RCa09USTNOakZrWVRBMU9XRXpaVEZoTlNJc0lDSnVaWGgwWDNWeWJDSTZJQ0lpZlE9PQ==|70a72e6e771deccf2e23385f1bcf4a32fb994c02c21fe37aa969d1a2d7cfd2f4"', 'X-Scheme': 'http', 'X-Original-Uri': '/hub/oauth_callback?code=66q4WVNOIyxWEYHVLvTN&amp;state=eyJzdGF0ZV9pZCI6ICI2NzUwNzZjZmU5MTQ0OTBkOTI3NjFkYTA1OWEzZTFhNSIsICJuZXh0X3VybCI6ICIifQ%3D%3D', 'X-Forwarded-Proto': 'http,http', 'X-Forwarded-Port': '80,31212', 'X-Forwarded-Host': 'fbn-jph:31212', 'X-Forwarded-For': '172.17.0.1,172.17.0.7', 'X-Real-Ip': '172.17.0.1', 'Connection': 'close', 'Host': 'fbn-jph:31212'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1512, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 328, in login_user
        authenticated = yield self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 227, in get_authenticated_user
        authenticated = yield self.authenticate(handler, data)
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/generic.py", line 120, in authenticate
        resp = yield http_client.fetch(req)
    tornado.httpclient.HTTPError: HTTP 403: Forbidden
```

Its not clear to me what url its trying to access, any pointers or help would be much appreciated. I'm running this locally using minikube with the following config:

```
proxy:
  secretToken: "<output from openssl rand -hex 32>"
  service:
    type: NodePort
    nodePorts:
      http: 31212

ingress:
    enabled: true
    hosts:
     - fbn-jph

auth:
  type: custom
  custom:
    className: "oauthenticator.generic.GenericOAuthenticator"
    config:
      client_id: "my-okta-client-id"
      client_secret: "my-okta-client-secret"
      token_url: "https://my-app.okta.com/oauth2/my-app-id/v1/token"
      authorize_url: "https://my-app.okta.com/oauth2/my-app-id/v1/authorize"

hub:
  extraEnv:
    OAUTH_CALLBACK_URL: "http://fbn-jph:31212/hub/oauth_callback"
    OAUTH2_AUTHORIZE_URL: "https://my-app.okta.com/oauth2/my-app-id/v1/authorize"
    OAUTH2_TOKEN_URL: "https://my-app.okta.com/oauth2/my-app-id/v1/token"
    OAUTH2_USERDATA_URL: "https://my-app.okta.com/oauth2/my-app-id/v1/userinfo"
```

**Comment by aurashn** [comment]
Hi Rizwan,

Were you able to solve this problem. I am noticing the same thing.

**Comment by rizwansaeed** [comment]
We resolved it by requesting a scope as part of the authorise url e.g "https://my-app.okta.com/oauth2/my-app-id/v1/authorize?scope=openid email"

Hope that helps

**Comment by aurashn** [comment]
Thanks that solved the issue for me as well.
