### ISSUE TITLE
tornado.httpclient.HTTPClientError: HTTP 401: Unauthorized in AzureAdOAuthenticator

### ISSUE THREAD

**Issue by scivm** [jupyterhub/oauthenticator#322]
I have the following zero to jupyterhub setup and am trying to enable Azure active directory with the AzureAdOAuthenticator.   The screen gives a 500 response and in the logs I am seeing a tornado.httpclient.HTTPClientError: HTTP 401: Unauthorized error.

```
hub:
  extraEnv:
    AAD_TENANT_ID: "xxxx"
  image:
    name: jupyterhub/k8s-hub
    tag: 0.9-17c3f1d

spec:
  env:
    - name: AAD_TENANT_ID
      value: xxxx

auth:
    type: custom
    custom:
      className: "oauthenticator.azuread.AzureAdOAuthenticator"
      config:
        client_id: "xxxx"
        client_secret: "xxxx"
        oauth_callback_url: "http://xxx/hub/oauth_callback"
        tenant_id: "xxxx"
```

```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 209, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 655, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 383, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/azuread.py", line 96, in authenticate
        resp = yield http_client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 401: Unauthorized
```

**Comment by Dmitry1987** [comment]
Same story with me but on GitLab... someone please help! :) 

My logs are like this in debug mode:

```
jupyterhub       | [I 2019-12-20 06:36:51.530 JupyterHub oauth2:100] OAuth redirect: 'http://notebooks.mydomain.com/hub/oauth_callback'
jupyterhub       | [I 2019-12-20 06:36:51.531 JupyterHub log:158] 302 GET /hub/oauth_login?next= -> https://gitlab.com/oauth/authorize?redirect_uri=http%3A%2F%2Fnotebooks.mydomain.com%2Fhub%2Foauth_callback&client_id=xxxxxxxxx&response_type=code&state=[secret]&scope=read_user (@myipaddress) 1.70ms
jupyterhub       | [E 2019-12-20 06:36:51.965 JupyterHub web:1670] Uncaught exception GET /hub/oauth_callback?code=976cbc888588faee8839cd0dcabd1e8109fddbc2ca33685ad827c386b5cc7ac3&state=xxxxx%3D%3D (myipaddress)
jupyterhub       |     HTTPServerRequest(protocol='http', host='notebooks.mydomain.com', method='GET', uri='/hub/oauth_callback?code=xxxxx&state=xxxxx%3D%3D', version='HTTP/1.1', remote_ip='myipaddress')
jupyterhub       |     Traceback (most recent call last):
jupyterhub       |       File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
jupyterhub       |         result = yield result
jupyterhub       |       File "/opt/conda/lib/python3.6/site-packages/oauthenticator/oauth2.py", line 207, in get
jupyterhub       |         user = await self.login_user()
jupyterhub       |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 473, in login_user
jupyterhub       |         authenticated = await self.authenticate(data)
jupyterhub       |       File "/opt/conda/lib/python3.6/site-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
jupyterhub       |         authenticated = await maybe_future(self.authenticate(handler, data))
jupyterhub       |       File "/opt/conda/lib/python3.6/site-packages/oauthenticator/gitlab.py", line 130, in authenticate
jupyterhub       |         self.gitlab_version = await self._get_gitlab_version(access_token)
jupyterhub       |       File "/opt/conda/lib/python3.6/site-packages/oauthenticator/gitlab.py", line 182, in _get_gitlab_version
jupyterhub       |         resp = await AsyncHTTPClient().fetch(req, raise_error=True)
jupyterhub       |     tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
jupyterhub       |
jupyterhub       | [D 2019-12-20 06:36:51.966 JupyterHub base:880] No template for 500
jupyterhub       | [E 2019-12-20 06:36:51.967 JupyterHub log:150] {
jupyterhub       |       "X-Real-Ip": "ipaddress",
jupyterhub       |       "X-Forwarded-Server": "bfbbe8f3b368",
jupyterhub       |       "X-Forwarded-Proto": "http,http",
jupyterhub       |       "X-Forwarded-Port": "80,80",
jupyterhub       |       "X-Forwarded-Host": "notebooks.mydomain.com",
jupyterhub       |       "X-Forwarded-For": "ipaddress,::ffff:172.31.0.2",
jupyterhub       |       "Upgrade-Insecure-Requests": "1",
jupyterhub       |       "Referer": "http://notebooks.mydomain.com/hub/login",
jupyterhub       |       "Cookie": "oauthenticator-state=\"2|1:0|10:1576823811|20:oauthenticator-state|120:xxxxxx==|xxxxxxxx\"",
jupyterhub       |       "Accept-Language": "en-US,en;q=0.9",
jupyterhub       |       "Accept-Encoding": "gzip, deflate",
jupyterhub       |       "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
jupyterhub       |       "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/myipadderss Safari/537.36",
jupyterhub       |       "Host": "notebooks.mydomain.com",
jupyterhub       |       "Connection": "close"
jupyterhub       |     }
jupyterhub       | [E 2019-12-20 06:36:51.967 JupyterHub log:158] 500 GET /hub/oauth_callback?code=[secret]&state=[secret] (@myipaddress) 82.25ms
jupyterhub       | [D 2019-12-20 06:40:17.958 JupyterHub proxy:686] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
jupyterhub       | 06:40:17.962 - info: [ConfigProxy] 200 GET /api/routes


```

**Comment by Dmitry1987** [comment]
found the reason... in my case it was wrong scope of permissions, I put only "read_user" but this thing wants "api read_repository write_repository" as a scope. 

```
c.GitLabOAuthenticator.scope = ['api read_repository write_repository']
```
Maybe it can help with Azure as well :)

**Comment by scivm** [comment]
There were 2 issues.  First is that an azure app in azure active directory defaults to oauth 1.  You need to go into the manifest and change it to 2.

Second issue was a bad secret.  

Best way to troubleshoot is make a simple python script that logs in with your clientid, tenantid and secret.   Get that working before you even try with jupyterhub.
