### ISSUE TITLE
JupyterHub single-user server requires notebook >= 4.0

### ISSUE THREAD

**Issue by kenenbek** [jupyterhub/oauthenticator#325]
I build and run Dockerfile from [here](https://github.com/jupyterhub/oauthenticator/tree/master/examples/full):

```
docker build -t jupyterhub-oauth .
docker run -it -p 9999:8000 --env-file=env jupyterhub-oauth
```

After authentification I got: 
```
[D 2019-12-19 18:45:35.109 JupyterHub user:542] Calling Spawner.start for kenenbek
[I 2019-12-19 18:45:35.113 JupyterHub spawner:1387] Spawning jupyterhub-singleuser --port=38765
[D 2019-12-19 18:45:35.284 JupyterHub spawner:1084] Polling subprocess every 30s
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 24, in <module>
    import notebook
ModuleNotFoundError: No module named 'notebook'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyterhub-singleuser", line 6, in <module>
    from jupyterhub.singleuser import main
  File "/opt/conda/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 26, in <module>
    raise ImportError("JupyterHub single-user server requires notebook >= 4.0")
ImportError: JupyterHub single-user server requires notebook >= 4.0
```

How can I fix it?

**Comment by minrk** [comment]
This can be fixed by installing the notebook package: `python3 -m pip install notebook`

The example linked is meant for use with users in their own containers, e.g. DockerSpawner

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
