### ISSUE TITLE
AttributeError: get_authenticated_username

### ISSUE THREAD

**Issue by Chekov2k** [jupyterhub/oauthenticator#33]
Hi,

I just tried this module and am getting the following error:
```
May 13 23:34:06 mysql jupyterhub: Traceback (most recent call last):
May 13 23:34:06 mysql jupyterhub: File "/usr/lib64/python3.4/site-packages/tornado/web.py", line 1445, in _execute
May 13 23:34:06 mysql jupyterhub: result = yield result
May 13 23:34:06 mysql jupyterhub: File "/usr/lib/python3.4/site-packages/oauthenticator/google.py", line 56, in get
May 13 23:34:06 mysql jupyterhub: username = yield self.authenticator.get_authenticated_username(self, None)
May 13 23:34:06 mysql jupyterhub: AttributeError: 'GoogleOAuthenticator' object has no attribute 'get_authenticated_username'
May 13 23:34:06 mysql jupyterhub: [E 2016-05-13 23:34:06.174 JupyterHub log:99] {
May 13 23:34:06 mysql jupyterhub: "Referer": "https://accounts.google.com/o/oauth2/auth?response_type=code&scope=openid+email&redirect_uri=https%3A%2F%2Fmysql.hessvo-uva.vm.surfsara.nl%3A8000%2Fhub%2Foauth_callback&client_id=875300024863-44scqeh9pgr26gog3m7fbtbt6tadgelp.apps.googleusercontent.com",
May 13 23:34:06 mysql jupyterhub: "Dnt": "1",
May 13 23:34:06 mysql jupyterhub: "X-Forwarded-For": "84.83.204.215",
May 13 23:34:06 mysql jupyterhub: "X-Forwarded-Port": "8000",
May 13 23:34:06 mysql jupyterhub: "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
May 13 23:34:06 mysql jupyterhub: "Cookie": "surfsaranl_cookiecontrol=yes",
May 13 23:34:06 mysql jupyterhub: "Connection": "close",
May 13 23:34:06 mysql jupyterhub: "Host": "mysql.hessvo-uva.vm.surfsara.nl:8000",
May 13 23:34:06 mysql jupyterhub: "Accept-Language": "en-us",
May 13 23:34:06 mysql jupyterhub: "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17",
May 13 23:34:06 mysql jupyterhub: "Accept-Encoding": "gzip, deflate",
May 13 23:34:06 mysql jupyterhub: "X-Forwarded-Proto": "https"
May 13 23:34:06 mysql jupyterhub: }
```

**Comment by Chekov2k** [comment]
Apparently you have to change it to get_authenticated_user and it doesn't crash at least ;-)

**Comment by benjamin-heasly** [comment]
Greetings!

I experienced same problem.  Changing `get_authenticated_username` -> `get_authenticated_user` fixed it for me.  I can now use the Google oauth.  Cool!

Here is a PR: https://github.com/jupyterhub/oauthenticator/pull/34
