### ISSUE TITLE
Spawn failed when using GitHubOAuthenticator

### ISSUE THREAD

**Issue by rohitsanj** [jupyterhub/oauthenticator#346]
### Problem
I have configured jupyterhub to be authenticated with GitHub OAuth. When I tried to login the first time, it threw some error.. I figured it was because it there was no Unix user with my GitHub username. So I created one, after which upon reloading the page, it seems to start loading the server until it fails due to a timeout. 

Here is the screenshot:
![Screenshot 2020-04-01 at 1 37 02
PM](https://user-images.githubusercontent.com/39169550/78113799-e7cbfb00-741d-11ea-980e-0b5d788cb8d1.png)

### `jupyterhub_config.py`
```python
# GitHub Authenticator

from oauthenticator.github import GitHubOAuthenticator
c.JupyterHub.authenticator_class = GitHubOAuthenticator
c.GitHubOAuthenticator.oauth_callback_url = 'http://xxx.xxx.xxx.xxx:8000/hub/oauth_callback'
c.GitHubOAuthenticator.client_id = 'xxx'
c.GitHubOAuthenticator.client_secret = 'xxx'
c.GitHubOAuthenticator.admin_users = { 'rohitsanj'}
```

### Logs
<details><summary>Click here</summary>
<p>
```
Apr 01 07:27:11 localhost jupyterhub[1723]: [E 2020-04-01 07:27:11.476 JupyterHub log:174] 500 GET /hub/spawn-pending/rohitsanj (rohitsanj@::ffff:106.51.30.112) 8.91ms
Apr 01 07:27:12 localhost jupyterhub[1723]: [I 2020-04-01 07:27:12.280 JupyterHub spawner:1417] Spawning jupyterhub-singleuser --port=53207 --NotebookApp.default_url=/lab
Apr 01 07:27:12 localhost jupyterhub[1723]: Traceback (most recent call last):
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
Apr 01 07:27:12 localhost jupyterhub[1723]:     value = obj._trait_values[self.name]
Apr 01 07:27:12 localhost jupyterhub[1723]: KeyError: 'runtime_dir'
Apr 01 07:27:12 localhost jupyterhub[1723]: During handling of the above exception, another exception occurred:
Apr 01 07:27:12 localhost jupyterhub[1723]: Traceback (most recent call last):
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/bin/jupyterhub-singleuser", line 11, in <module>
Apr 01 07:27:12 localhost jupyterhub[1723]:     sys.exit(main())
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 660, in main
Apr 01 07:27:12 localhost jupyterhub[1723]:     return SingleUserNotebookApp.launch_instance(argv)
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/jupyter_core/application.py", line 270, in launch_instance
Apr 01 07:27:12 localhost jupyterhub[1723]:     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/traitlets/config/application.py", line 663, in launch_instance
Apr 01 07:27:12 localhost jupyterhub[1723]:     app.initialize(argv)
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 558, in initialize
Apr 01 07:27:12 localhost jupyterhub[1723]:     return super().initialize(argv)
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "<decorator-gen-7>", line 2, in initialize
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
Apr 01 07:27:12 localhost jupyterhub[1723]:     return method(app, *args, **kwargs)
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/notebook/notebookapp.py", line 1766, in initialize
Apr 01 07:27:12 localhost jupyterhub[1723]:     self.init_configurables()
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/notebook/notebookapp.py", line 1380, in init_configurables
Apr 01 07:27:12 localhost jupyterhub[1723]:     connection_dir=self.runtime_dir,
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
Apr 01 07:27:12 localhost jupyterhub[1723]:     return self.get(obj, cls)
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
Apr 01 07:27:12 localhost jupyterhub[1723]:     value = self._validate(obj, dynamic_default())
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/jupyter_core/application.py", line 100, in _runtime_dir_default
Apr 01 07:27:12 localhost jupyterhub[1723]:     ensure_dir_exists(rd, mode=0o700)
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
Apr 01 07:27:12 localhost jupyterhub[1723]:     os.makedirs(path, mode=mode)
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/usr/lib/python3.6/os.py", line 210, in makedirs
Apr 01 07:27:12 localhost jupyterhub[1723]:     makedirs(head, mode, exist_ok)
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/usr/lib/python3.6/os.py", line 210, in makedirs
Apr 01 07:27:12 localhost jupyterhub[1723]:     makedirs(head, mode, exist_ok)
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/usr/lib/python3.6/os.py", line 210, in makedirs
Apr 01 07:27:12 localhost jupyterhub[1723]:     makedirs(head, mode, exist_ok)
Apr 01 07:27:12 localhost jupyterhub[1723]:   [Previous line repeated 1 more time]
Apr 01 07:27:12 localhost jupyterhub[1723]:   File "/usr/lib/python3.6/os.py", line 220, in makedirs
Apr 01 07:27:12 localhost jupyterhub[1723]:     mkdir(name, mode)
Apr 01 07:27:12 localhost jupyterhub[1723]: PermissionError: [Errno 13] Permission denied: '/home/rohitsanj'
Apr 01 07:27:13 localhost jupyterhub[1723]: [I 2020-04-01 07:27:13.254 JupyterHub log:174] 302 GET /hub/spawn/rohitsanj -> /hub/spawn-pending/rohitsanj (rohitsanj@::ffff:106.51
Apr 01 07:27:13 localhost jupyterhub[1723]: [I 2020-04-01 07:27:13.290 JupyterHub pages:347] rohitsanj is pending spawn
Apr 01 07:27:13 localhost jupyterhub[1723]: [I 2020-04-01 07:27:13.292 JupyterHub log:174] 200 GET /hub/spawn-pending/rohitsanj (rohitsanj@::ffff:106.51.30.112) 6.06ms
Apr 01 07:27:22 localhost jupyterhub[1723]: ERROR:asyncio:Task exception was never retrieved
Apr 01 07:27:22 localhost jupyterhub[1723]: future: <Task finished coro=<BaseHandler.spawn_single_user() done, defined at /opt/jupyterhub/lib/python3.6/site-packages/jupyterhub
Apr 01 07:27:22 localhost jupyterhub[1723]: Traceback (most recent call last):
Apr 01 07:27:22 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 939, in spawn_single_user
Apr 01 07:27:22 localhost jupyterhub[1723]:     timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future
Apr 01 07:27:22 localhost jupyterhub[1723]: tornado.util.TimeoutError: Timeout
Apr 01 07:27:22 localhost jupyterhub[1723]: During handling of the above exception, another exception occurred:
Apr 01 07:27:22 localhost jupyterhub[1723]: Traceback (most recent call last):
Apr 01 07:27:22 localhost jupyterhub[1723]:   File "/opt/jupyterhub/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 972, in spawn_single_user
Apr 01 07:27:22 localhost jupyterhub[1723]:     % (status, spawner._log_name),
Apr 01 07:27:22 localhost jupyterhub[1723]: tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for rohitsanj may contain detai
Apr 01 07:27:41 localhost jupyterhub[1723]: [W 2020-04-01 07:27:41.682 JupyterHub user:692] rohitsanj's server never showed up at http://127.0.0.1:53207/user/rohitsanj/ after 3
Apr 01 07:27:41 localhost jupyterhub[1723]: [E 2020-04-01 07:27:41.693 JupyterHub gen:599] Exception in Future <Task finished coro=<BaseHandler.spawn_single_user.<locals>.finis
Apr 01 07:27:41 localhost jupyterhub[1723]:     Traceback (most recent call last):
Apr 01 07:27:41 localhost jupyterhub[1723]:       File "/opt/jupyterhub/lib/python3.6/site-packages/tornado/gen.py", line 593, in error_callback
Apr 01 07:27:41 localhost jupyterhub[1723]:         future.result()
Apr 01 07:27:41 localhost jupyterhub[1723]:       File "/opt/jupyterhub/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 852, in finish_user_spawn
Apr 01 07:27:41 localhost jupyterhub[1723]:         await spawn_future
Apr 01 07:27:41 localhost jupyterhub[1723]:       File "/opt/jupyterhub/lib/python3.6/site-packages/jupyterhub/user.py", line 668, in spawn
Apr 01 07:27:41 localhost jupyterhub[1723]:         await self._wait_up(spawner)
Apr 01 07:27:41 localhost jupyterhub[1723]:       File "/opt/jupyterhub/lib/python3.6/site-packages/jupyterhub/user.py", line 715, in _wait_up
Apr 01 07:27:41 localhost jupyterhub[1723]:         raise e
Apr 01 07:27:41 localhost jupyterhub[1723]:       File "/opt/jupyterhub/lib/python3.6/site-packages/jupyterhub/user.py", line 683, in _wait_up
Apr 01 07:27:41 localhost jupyterhub[1723]:         http=True, timeout=spawner.http_timeout, ssl_context=ssl_context
Apr 01 07:27:41 localhost jupyterhub[1723]:       File "/opt/jupyterhub/lib/python3.6/site-packages/jupyterhub/utils.py", line 234, in wait_for_http_server
Apr 01 07:27:41 localhost jupyterhub[1723]:         timeout=timeout,
Apr 01 07:27:41 localhost jupyterhub[1723]:       File "/opt/jupyterhub/lib/python3.6/site-packages/jupyterhub/utils.py", line 177, in exponential_backoff
Apr 01 07:27:41 localhost jupyterhub[1723]:         raise TimeoutError(fail_message)
Apr 01 07:27:41 localhost jupyterhub[1723]:     TimeoutError: Server at http://127.0.0.1:53207/user/rohitsanj/ didn't respond in 30 seconds
```
</p>
</details>

### My analysis
Seems like it is running into a `PermissionDenied` error, but the service is configured to run from root user.
```
[Unit]
Description=JupyterHub
After=syslog.target network.target

[Service]
User=root
Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/jupyterhub/bin"
ExecStart=/opt/jupyterhub/bin/jupyterhub -f /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py

[Install]
WantedBy=multi-user.target
```

I'm not sure how to fix this. Also one more thing, 
`c.LocalAuthenticator.create_system_users = True` is not working at all, neither PAM nor GitHub OAuth. Is it yet to be implemented for oauthenticator?

I'm using an Ubuntu 16.04 machine to run JupyterHub.

**Comment by rohitsanj** [comment]
Just found out what was wrong.. somehow a new user directory was not being created when I did `adduser rohitsanj`

Fixed it by going to `/etc/login.defs` and adding the line `CREATE_HOME yes`
[source](https://askubuntu.com/questions/374870/home-directory-not-being-created)
