### ISSUE TITLE
GenericOAuthenticator with Moodle got errors because of empty POST body

### ISSUE THREAD

**Issue by owenliang** [jupyterhub/oauthenticator#367]
I am following this: https://oauthenticator.readthedocs.io/en/latest/getting-started.html#moodle-setup

and jupyterhub print this error:

```
    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.8/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/root/miniconda3/lib/python3.8/site-packages/oauthenticator/oauth2.py", line 213, in get
        user = await self.login_user()
      File "/root/miniconda3/lib/python3.8/site-packages/jupyterhub/handlers/base.py", line 699, in login_user
        authenticated = await self.authenticate(data)
      File "/root/miniconda3/lib/python3.8/site-packages/jupyterhub/auth.py", line 383, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/root/miniconda3/lib/python3.8/site-packages/oauthenticator/generic.py", line 135, in authenticate
        resp = await http_client.fetch(req)
      File "/root/miniconda3/lib/python3.8/site-packages/tornado/curl_httpclient.py", line 232, in _process_queue
        self._curl_setup_request(
      File "/root/miniconda3/lib/python3.8/site-packages/tornado/curl_httpclient.py", line 455, in _curl_setup_request
        raise ValueError(
    ValueError: Body must not be None for method POST (unless allow_nonstandard_methods is true)
```

and I think we should add allow_nonstandard_methods=True here: https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/generic.py#L132

I think an empty post body is fine,  tornado may be  too strict with default behavior.

**Comment by consideRatio** [comment]
@owenliang I think this is fixed in #198, but it isn't released yet.

I'm actually looking for someone to help me verify a new set of instructions for Moodle, which may help you also get everything to work, do you have time to help me?

Could you try if your JupyterHub would work when the currently unreleased version of oauthenticator is used, and where you __don't set__ `c.GenericOAuthenticator.userdata_method = 'POST'` but instead let it be the default of `GET`?

It would help me with relevant input to #376
